/**
 * @file Фикстуры сущности `post` для использования в модульных тестах
 * и сквозных сценариях Playwright.
 *
 * Все моки исключены из анализа покрытия кода, так как не содержат
 * тестируемой логики.
 */
import {createPost} from "../model/createPost";
import img from "shared/icons/img-CTA.jpg";
import img2 from "shared/icons/img-template.jpg";
import {profileUserMock} from "entities/user";
import {postTagsMock} from "entities/tag";

export const profileAlbum1PostsMock = [
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAB",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAV",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 2,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAU",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
];

export const profileAlbum2PostsMock = [
    createPost({
        id: 6,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAB",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAV",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 2,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAU",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 4,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAv",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAA",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 4,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAv",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
];

export const postMock = createPost({
    id: 1,
    ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAB",
    name: "Post title",
    description: "Description Description Description Description Description Description Description Description Description",
    author: profileUserMock,
    likes: 999000000,
    comments: 999000000,
    reports: 999000000,
    commentList: [],
    tagsList: postTagsMock,
    checkStatus: "checked",
    AIStatus: "good",
    imageUrl: img,
    createdAt: "2025-09-01T00:00:00.000Z",
});

export const galleryPostsMock = [
    createPost({
        id: 6,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAa",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 1,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAq",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img2,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 2,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAv",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img2,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAb",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img2,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 4,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAm",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 3,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAh",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img2,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
    createPost({
        id: 4,
        ULID: "01ARZ3NDEKTSV4RRFFQ69G5FAj",
        name: "post 1 name",
        description: "post 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 namepost 1 name",
        author: profileUserMock,
        likes: 1,
        comments: 1,
        reports: 1,
        commentList: [],
        tagsList: [],
        checkStatus: "checked",
        AIStatus: "good",
        imageUrl: img,
        createdAt: "2026-03-24T18:48:16.175Z",
    }),
];
